name: odds
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:

  animated_text_kit: ^4.2.2
  animated_splash_screen: ^1.3.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  dio: ^5.4.1
  csv: ^6.0.0
  file_picker: ^6.2.0
  open_file: ^3.3.2
  path_provider: ^2.1.2
  # flutter_embed_unity: ^1.0.4
  flutter_unity_widget: ^2022.2.0
  pointer_interceptor: ^0.10.1
  video_player: ^2.8.3

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/
